import jsPDF from 'jspdf'

function money(value) {
  return `$${Number(value || 0).toLocaleString()}`
}

export function exportTripPDF(trip, itinerary = {}, weather = null) {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 20

  const addLine = (text, x = 14, fontSize = 10, style = 'normal') => {
    doc.setFontSize(fontSize)
    doc.setFont('helvetica', style)
    const lines = doc.splitTextToSize(String(text), pageWidth - 28)
    lines.forEach(line => {
      if (y > 270) {
        doc.addPage()
        y = 20
      }
      doc.text(line, x, y)
      y += fontSize * 0.6
    })
    y += 2
  }

  const addSection = title => {
    y += 4
    doc.setFillColor(37, 99, 235)
    doc.rect(14, y - 5, pageWidth - 28, 8, 'F')
    doc.setTextColor(255, 255, 255)
    addLine(title, 16, 11, 'bold')
    doc.setTextColor(0, 0, 0)
    y += 2
  }

  doc.setFillColor(37, 99, 235)
  doc.rect(0, 0, pageWidth, 30, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.text('YatraAI Travel Itinerary', 14, 20)
  doc.setTextColor(0, 0, 0)
  y = 40

  addSection('Trip Details')
  addLine(`Destination: ${trip.destination}`)
  addLine(`Dates: ${trip.start_date} to ${trip.end_date}`)
  addLine(`Budget: ${money(trip.budget)} USD`)
  addLine(`Travelers: ${trip.travelers}`)
  addLine(`Interests: ${trip.interests || 'Not specified'}`)
  if (itinerary.summary) addLine(`Summary: ${itinerary.summary}`)

  if (weather) {
    addSection('Weather Summary')
    addLine(`${weather.city}: ${Math.round(weather.temperature)} C, ${weather.description}`)
    addLine(`Humidity: ${weather.humidity}% | Wind: ${weather.wind_speed} m/s`)
  }

  if (itinerary.days?.length > 0) {
    addSection('Day-wise Itinerary')
    itinerary.days.forEach(day => {
      addLine(`Day ${day.day}: ${day.theme || 'Trip Plan'} (${day.date || 'Date not set'})`, 14, 11, 'bold')
      if (day.places?.length) addLine(`Places: ${day.places.map(p => (typeof p === 'object' ? p.name : p)).join(', ')}`)
      if (day.activities?.length) addLine(`Activities: ${day.activities.join(', ')}`)
      if (day.timing?.length) day.timing.forEach(item => addLine(`- ${item}`, 18, 9))
      if (day.estimated_cost) addLine(`Estimated Cost: ${money(day.estimated_cost)}`)
      if (day.tips) addLine(`Tip: ${day.tips}`)
      y += 3
    })
  }

  if (itinerary.hotels?.length > 0) {
    addSection('Hotel Recommendations')
    itinerary.hotels.forEach(hotel => {
      addLine(`${hotel.name} - Rating: ${hotel.rating || 'N/A'} | ${hotel.price_range || 'Price not listed'}`, 14, 10, 'bold')
      addLine(`${hotel.description || ''} ${hotel.location ? `| ${hotel.location}` : ''}`)
    })
  }

  if (itinerary.flights?.length > 0) {
    addSection('Flight Suggestions')
    itinerary.flights.forEach(flight => {
      addLine(`${flight.airline || 'Airline'}: ${flight.departure_city || 'Origin'} to ${flight.destination_city || trip.destination} | ${money(flight.estimated_cost)} | ${flight.duration || 'Duration not listed'}`)
    })
  }

  addSection('Budget Summary')
  addLine(`Total Budget: ${money(trip.budget)}`)
  if (itinerary.total_estimated_cost) {
    addLine(`Estimated Trip Cost: ${money(itinerary.total_estimated_cost)}`)
    const remaining = Number(trip.budget || 0) - Number(itinerary.total_estimated_cost || 0)
    addLine(`Remaining: ${money(remaining)} ${remaining >= 0 ? '(Within budget)' : '(Over budget)'}`)
  }

  const pageCount = doc.internal.getNumberOfPages()
  for (let page = 1; page <= pageCount; page += 1) {
    doc.setPage(page)
    doc.setFontSize(8)
    doc.setTextColor(150)
    doc.text(`Generated by YatraAI | Page ${page} of ${pageCount}`, 14, 285)
  }

  doc.save(`YatraAI_${trip.destination.replace(/[^a-zA-Z0-9]/g, '_')}_itinerary.pdf`)
}
